Repository CID15/aem-groovy-console, pull requests merged in 2024-08, with the labels that each got.

#17 Various updates for next release version
  README.md
  all/pom.xml
  bundle/pom.xml
  bundle/src/main/groovy/org/cid15/aem/groovy/console/constants/GroovyConsoleConstants.groovy
  pom.xml
  ui.apps.structure/pom.xml
  ui.apps/pom.xml
  ui.config/pom.xml
  ui.config/src/main/content/jcr_root/apps/groovyconsole/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-groovyconsole.config
  ui.config/src/main/content/jcr_root/apps/groovyconsole/osgiconfig/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-groovy-console.xml
  ui.content/pom.xml
Labels: size/L

#13 added retrieve option to avoid datatables warning
  ui.apps/src/main/content/jcr_root/apps/groovyconsole/clientlibs/js/audit.js
Labels: size/XS

#18 Update plugins to support Maven Central deployment
  bundle/pom.xml
  bundle/src/main/assembly/javadoc.xml
  bundle/src/main/javadoc/README
  pom.xml
Labels: size/M
